name: Generate GitHub Snake

on:
  workflow_dispatch:  # manual trigger

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: shaqibqureshi

      - name: Push to output branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create output branch if it doesn't exist
          if ! git ls-remote --exit-code --heads origin output; then
            git checkout -b output
            git push origin output
          else
            git checkout output
          fi
          
          mkdir -p .
          mv snake.svg output/github-snake.svg
          git add output/github-snake.svg
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push origin output --force

